from __future__ import annotations

from dataclasses import dataclass
import hashlib
import json
import pathlib
import re

from attractor_dot import parse_dot
from attractor_model import AttractorModel, AttractorStep, build_model, normalize_step_id


PACK_VERSION = "0.1.0"
VAR_REF_RE = re.compile(r"\{\{([A-Za-z_][A-Za-z0-9_]*)\}\}")
DOLLAR_VAR_RE = re.compile(r"\$([a-z_][a-z0-9_]*)|\$\{([a-z_][a-z0-9_]*)\}")


@dataclass
class CompileResult:
    formula_name: str
    text: str
    warnings: list[str]


def compile_dot(text: str, formula_name: str | None = None, source_label: str = "<memory>") -> CompileResult:
    display_label = source_display_label(source_label)
    graph = parse_dot(text, source=display_label)
    resolved_name = formula_name or graph.graph_attrs.get("gc_formula") or fallback_formula_name(display_label, graph.name)
    model = build_model(graph, resolved_name)
    rendered = render_formula(model, text, display_label)
    return CompileResult(model.formula_name, rendered.text, rendered.warnings)


@dataclass
class RenderedFormula:
    text: str
    warnings: list[str]


def fallback_formula_name(source_label: str, graph_name: str) -> str:
    stem = pathlib.Path(source_label).stem if source_label and source_label != "<memory>" else graph_name
    name = normalize_step_id(stem or "workflow")
    return f"mol-attractor-{name}"


def source_display_label(source_label: str) -> str:
    if not source_label or source_label == "<memory>":
        return "<memory>"
    path = pathlib.PurePath(source_label)
    if path.is_absolute():
        return path.name
    return source_label.replace("\\", "/")


def render_formula(model: AttractorModel, source_text: str, source_label: str) -> RenderedFormula:
    warnings: list[str] = []
    aliases: dict[str, str] = {}
    var_defaults: dict[str, str] = {}
    required: set[str] = set()

    goal = model.goal.strip()
    if goal:
        exact = _exact_var_ref(goal)
        if exact:
            aliases["goal"] = exact
            required.add(exact)
        elif _contains_var_ref(goal):
            required.add("goal")
            warnings.append("graph goal mixes literals and variables; generated formula requires goal at runtime")
        else:
            var_defaults["goal"] = goal

    rendered_steps = [_render_step(step, aliases) for step in model.steps]
    body_description = "Terminal latch for the generated Attractor workflow."
    if goal:
        body_description += "\n\nGoal: {{goal}}" if "goal" in required else "\n\nGoal: {{goal}}"
    body_description = _normalize_vars(body_description, aliases)
    rendered_body = {
        "id": "body",
        "title": "Attractor body scope",
        "description": body_description,
        "needs": [step.step_id for step in model.steps],
        "metadata": {
            "gc.kind": "scope",
            "gc.scope_name": "attractor",
            "gc.scope_role": "body",
        },
    }

    all_var_text = [_normalize_vars(model.description, aliases), rendered_body["description"]]
    for step in rendered_steps:
        all_var_text.extend([step["title"], step["description"], step["metadata"].get("gc.run_target", "")])
    for name in _collect_vars("\n".join(all_var_text)):
        if name not in var_defaults:
            required.add(name)

    lines: list[str] = [
        f"# Generated by gascity-packs attractor {PACK_VERSION}",
        f"# source = {_toml_string(source_label)}",
        f"# source_sha256 = {_toml_string(hashlib.sha256(source_text.encode('utf-8')).hexdigest())}",
        f"formula = {_toml_string(model.formula_name)}",
        "version = 2",
        'contract = "graph.v2"',
        f"description = {_toml_string(_normalize_vars(model.description, aliases))}",
        "",
    ]
    if var_defaults or required:
        lines.append("[vars]")
        for name in sorted(var_defaults):
            lines.append("")
            lines.append(f"[vars.{name}]")
            lines.append(f"description = {_toml_string(f'Attractor variable {name}')}")
            lines.append(f"default = {_toml_string(_normalize_vars(var_defaults[name], aliases))}")
        for name in sorted(required):
            if name in var_defaults:
                continue
            lines.append("")
            lines.append(f"[vars.{name}]")
            lines.append(f"description = {_toml_string(f'Attractor variable {name}')}")
            lines.append("required = true")
        lines.append("")

    _append_step(lines, rendered_body)
    for step in rendered_steps:
        _append_step(lines, step)

    return RenderedFormula("\n".join(lines).rstrip() + "\n", warnings)


def _render_step(step: AttractorStep, aliases: dict[str, str]) -> dict[str, object]:
    if step.kind == "tool":
        base_description = (
            "Run this command in the assigned workspace and report the result.\n\n"
            "```bash\n"
            f"{step.command}\n"
            "```"
        )
    else:
        base_description = step.prompt
    description = _normalize_vars(base_description, aliases) + CLOSE_CONTRACT
    metadata = {
        "gc.scope_ref": "body",
        "gc.scope_role": "member",
        "gc.on_fail": "abort_scope",
        "attractor.node_id": step.node_id,
        "attractor.step_id": step.step_id,
    }
    if step.node_shape:
        metadata["attractor.node_shape"] = step.node_shape
    if step.run_target:
        metadata["gc.run_target"] = _normalize_vars(step.run_target, aliases)

    rendered: dict[str, object] = {
        "id": step.step_id,
        "title": _normalize_vars(step.title, aliases),
        "description": description,
        "needs": step.needs,
        "metadata": metadata,
    }
    if step.max_retries is not None and step.max_retries > 0:
        rendered["retry"] = {"max_attempts": step.max_retries + 1, "on_exhausted": "hard_fail"}
    return rendered


CLOSE_CONTRACT = """

Attractor close contract:

- On success, close this bead with `gc.outcome=pass`.
- On failure, close it with `gc.outcome=fail`, `gc.failure_class`, and `gc.failure_reason`.
- If you produce structured output for later steps, set `gc.output_json` before closing.
"""


def _append_step(lines: list[str], step: dict[str, object]) -> None:
    lines.append("[[steps]]")
    lines.append(f"id = {_toml_string(str(step['id']))}")
    lines.append(f"title = {_toml_string(str(step['title']))}")
    needs = step.get("needs") or []
    lines.append(f"needs = {_toml_array([str(item) for item in needs])}")
    lines.append(f"description = {_toml_string(str(step['description']))}")
    lines.append(f"metadata = {_toml_inline_table(step['metadata'])}")
    retry = step.get("retry")
    if isinstance(retry, dict):
        lines.append("")
        lines.append("[steps.retry]")
        lines.append(f"max_attempts = {int(retry['max_attempts'])}")
        lines.append(f"on_exhausted = {_toml_string(str(retry['on_exhausted']))}")
    lines.append("")


def _normalize_vars(text: str, aliases: dict[str, str]) -> str:
    def dollar_repl(match: re.Match[str]) -> str:
        name = match.group(1) or match.group(2)
        return "{{" + aliases.get(name, name) + "}}"

    text = DOLLAR_VAR_RE.sub(dollar_repl, text)
    for src, dst in aliases.items():
        text = text.replace("{{" + src + "}}", "{{" + dst + "}}")
    return text


def _exact_var_ref(text: str) -> str | None:
    normalized = _normalize_vars(text, {})
    match = VAR_REF_RE.fullmatch(normalized)
    if match:
        return match.group(1)
    return None


def _contains_var_ref(text: str) -> bool:
    return bool(VAR_REF_RE.search(_normalize_vars(text, {})))


def _collect_vars(text: str) -> set[str]:
    return {match.group(1) for match in VAR_REF_RE.finditer(text)}


def _toml_string(value: str) -> str:
    return json.dumps(value)


def _toml_array(values: list[str]) -> str:
    return "[" + ", ".join(_toml_string(value) for value in values) + "]"


def _toml_inline_table(values: object) -> str:
    if not isinstance(values, dict):
        raise TypeError("metadata must be a dict")
    parts = [f"{_toml_string(str(key))} = {_toml_string(str(values[key]))}" for key in sorted(values)]
    return "{ " + ", ".join(parts) + " }"
